development:
  adapter: mysql2
  database: Blog
  host: localhost
  username: root
  password: root
  encoding: utf8
production:
  adapter: mysql2
  database: Blog
  host: localhost
  username: root
  password: root
  encoding: utf8
